name       : clustershell
version    : 1.7.3
release    : 2
source     :
    - https://github.com/cea-hpc/clustershell/archive/v1.7.3.tar.gz : 05724cf189aae4585576faa5183eb9be97bf2993b1d0049b9e0e2689f76661fc
license    : LGPL-2.1
component  : system.utils
summary    : Clustershell is designed to run local or distant command in parallel
description: |
    ClusterShell is an event-driven open source Python library, designed to run local or distant commands in parallel on server farms or on large Linux clusters. It will take care of common issues encountered on HPC clusters, such as operating on groups of nodes, running distributed commands using optimized execution algorithms, as well as gathering results and merging identical outputs, or retrieving return codes. ClusterShell takes advantage of existing remote shell facilities already installed on your systems, like SSH
builddeps  : 
    - python-setuptools
rundeps    :
    - pyyaml
build      : |
    %python_setup
install    : |
    %python_install
